
import { CloudProvider, Severity, Status, AssetType, Misconfiguration } from './types';

export const MOCK_RECORDS: Misconfiguration[] = [
  // 8 IAM Records (40%)
  { id: 'ISS-001', cloud: CloudProvider.AWS, account: 'aws-prod-01', resourceType: AssetType.IAM, resourceName: 'overly-permissive-deployer', severity: Severity.CRITICAL, status: Status.OPEN, description: 'User "deploy-bot" has full AdministratorAccess.', remediation: 'Scope policy to only required S3 and EC2 actions.', detectedAt: '2024-05-01T10:00:00Z' },
  { id: 'ISS-002', cloud: CloudProvider.AZURE, account: 'azure-core', resourceType: AssetType.IAM, resourceName: 'mfa-disabled-global-admin', severity: Severity.CRITICAL, status: Status.OPEN, description: 'Global Admin account lacks Multi-Factor Authentication.', remediation: 'Enforce MFA via Conditional Access policy.', detectedAt: '2024-05-01T11:00:00Z' },
  { id: 'ISS-003', cloud: CloudProvider.GCP, account: 'gcp-data-lake', resourceType: AssetType.IAM, resourceName: 'primitive-owner-assigned', severity: Severity.HIGH, status: Status.OPEN, description: 'User has Owner role instead of granular IAM roles.', remediation: 'Assign "Storage Admin" and "Compute Viewer" instead.', detectedAt: '2024-05-02T09:00:00Z' },
  { id: 'ISS-004', cloud: CloudProvider.AWS, account: 'aws-stg-02', resourceType: AssetType.IAM, resourceName: 'unused-access-keys', severity: Severity.MEDIUM, status: Status.OPEN, description: 'Access keys have not been rotated for 180 days.', remediation: 'Deactivate keys and rotate credentials.', detectedAt: '2024-05-02T14:00:00Z' },
  { id: 'ISS-005', cloud: CloudProvider.AZURE, account: 'azure-main', resourceType: AssetType.IAM, resourceName: 'anonymous-access-granted', severity: Severity.HIGH, status: Status.OPEN, description: 'Storage Blob Data Contributor granted to Anonymous.', remediation: 'Remove anonymous role assignment from storage account.', detectedAt: '2024-05-03T08:00:00Z' },
  { id: 'ISS-006', cloud: CloudProvider.GCP, account: 'gcp-corp-01', resourceType: AssetType.IAM, resourceName: 'external-user-access', severity: Severity.HIGH, status: Status.OPEN, description: 'User from non-corp domain has project Editor access.', remediation: 'Remove external user from IAM project list.', detectedAt: '2024-05-03T10:00:00Z' },
  { id: 'ISS-007', cloud: CloudProvider.AWS, account: 'aws-prod-01', resourceType: AssetType.IAM, resourceName: 'wildcard-policy-detected', severity: Severity.CRITICAL, status: Status.OPEN, description: 'Policy allows Action: "*" on Resource: "*".', remediation: 'Define specific resource ARNs in the policy document.', detectedAt: '2024-05-03T16:00:00Z' },
  { id: 'ISS-008', cloud: CloudProvider.AZURE, account: 'azure-dev', resourceType: AssetType.IAM, resourceName: 'stale-service-principal', severity: Severity.LOW, status: Status.OPEN, description: 'Service principal has not logged in for 90 days.', remediation: 'Audit usage and delete service principal if obsolete.', detectedAt: '2024-05-04T02:00:00Z' },
  
  // 12 Other Records
  { id: 'ISS-009', cloud: CloudProvider.GCP, account: 'gcp-data-lake', resourceType: AssetType.STORAGE, resourceName: 'public-bucket-pii', severity: Severity.CRITICAL, status: Status.OPEN, description: 'Bucket "client-data-v2" is open to the internet.', remediation: 'Enable Uniform Bucket-Level Access and remove "allUsers".', detectedAt: '2024-05-04T05:00:00Z' },
  { id: 'ISS-010', cloud: CloudProvider.AWS, account: 'aws-prod-01', resourceType: AssetType.DB, resourceName: 'rds-unencrypted-at-rest', severity: Severity.HIGH, status: Status.OPEN, description: 'RDS instance lacks storage encryption.', remediation: 'Enable encryption using AWS KMS CMK.', detectedAt: '2024-05-04T09:00:00Z' },
  { id: 'ISS-011', cloud: CloudProvider.AZURE, account: 'azure-main', resourceType: AssetType.NETWORK, resourceName: 'rdp-open-to-anywhere', severity: Severity.HIGH, status: Status.OPEN, description: 'NSG allows RDP (3389) from any IP.', remediation: 'Restrict port 3389 to known corporate VPN IPs.', detectedAt: '2024-05-04T12:00:00Z' },
  { id: 'ISS-012', cloud: CloudProvider.GCP, account: 'gcp-corp-01', resourceType: AssetType.NETWORK, resourceName: 'default-vpc-active', severity: Severity.LOW, status: Status.OPEN, description: 'Default VPC exists in the production project.', remediation: 'Delete default VPC and use custom VPC instead.', detectedAt: '2024-05-04T15:00:00Z' },
  { id: 'ISS-013', cloud: CloudProvider.AWS, account: 'aws-stg-02', resourceType: AssetType.STORAGE, resourceName: 's3-logging-disabled', severity: Severity.MEDIUM, status: Status.OPEN, description: 'Access logging is not enabled for critical S3 bucket.', remediation: 'Enable server access logging to a separate audit bucket.', detectedAt: '2024-05-05T08:00:00Z' },
  { id: 'ISS-014', cloud: CloudProvider.AZURE, account: 'azure-dev', resourceType: AssetType.DB, resourceName: 'sql-auditing-disabled', severity: Severity.MEDIUM, status: Status.OPEN, description: 'Azure SQL auditing is not configured.', remediation: 'Enable auditing to a storage account or Log Analytics.', detectedAt: '2024-05-05T10:00:00Z' },
  { id: 'ISS-015', cloud: CloudProvider.GCP, account: 'gcp-data-lake', resourceType: AssetType.DB, resourceName: 'cloudsql-public-ip', severity: Severity.HIGH, status: Status.OPEN, description: 'Instance has a public IP assigned.', remediation: 'Disable public IP and use Private Service Access.', detectedAt: '2024-05-05T13:00:00Z' },
  { id: 'ISS-016', cloud: CloudProvider.AWS, account: 'aws-prod-01', resourceType: AssetType.NETWORK, resourceName: 'flow-logs-missing', severity: Severity.MEDIUM, status: Status.OPEN, description: 'VPC Flow Logs are not enabled.', remediation: 'Enable flow logs for all subnets in the VPC.', detectedAt: '2024-05-05T16:00:00Z' },
  { id: 'ISS-017', cloud: CloudProvider.AZURE, account: 'azure-main', resourceType: AssetType.STORAGE, resourceName: 'tls-outdated', severity: Severity.MEDIUM, status: Status.OPEN, description: 'Storage account allows TLS 1.0/1.1.', remediation: 'Minimum TLS version should be set to 1.2.', detectedAt: '2024-05-06T09:00:00Z' },
  { id: 'ISS-018', cloud: CloudProvider.AWS, account: 'aws-prod-01', resourceType: AssetType.STORAGE, resourceName: 'public-s3-detected', severity: Severity.CRITICAL, status: Status.OPEN, description: 'S3 bucket "public-assets" allows public read access.', remediation: 'Enable "Block Public Access" at the bucket level.', detectedAt: '2024-05-06T11:00:00Z' },
  { id: 'ISS-019', cloud: CloudProvider.GCP, account: 'gcp-corp-01', resourceType: AssetType.NETWORK, resourceName: 'ssh-open-internet', severity: Severity.HIGH, status: Status.OPEN, description: 'Firewall allows SSH from 0.0.0.0/0.', remediation: 'Modify firewall rule to restrict source IP ranges.', detectedAt: '2024-05-06T14:00:00Z' },
  { id: 'ISS-020', cloud: CloudProvider.AWS, account: 'aws-stg-02', resourceType: AssetType.DB, resourceName: 'unencrypted-ebs-volume', severity: Severity.MEDIUM, status: Status.OPEN, description: 'EBS volume attached to DB is unencrypted.', remediation: 'Snapshot volume and recreate as encrypted.', detectedAt: '2024-05-06T17:00:00Z' }
];

export const SEVERITY_COLORS: Record<Severity, string> = {
  [Severity.CRITICAL]: 'text-red-600 bg-white border-red-600',
  [Severity.HIGH]: 'text-orange-600 bg-white border-orange-600',
  [Severity.MEDIUM]: 'text-yellow-600 bg-white border-yellow-600',
  [Severity.LOW]: 'text-gray-400 bg-white border-gray-400'
};
